apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tyk-sre-app.fullname" . }}
  labels:
    {{- include "tyk-sre-app.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

#  - apiGroups: ["networking.k8s.io"]
#    resources: ["networkpolicies"]
#    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
