apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tyk-sre-app.fullname" . }}
  labels:
    {{- include "tyk-sre-app.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  PORT: {{ .Values.config.port | quote }}
  GRACEFUL_TIMEOUT: {{ .Values.config.gracefulTimeout | quote }}
