apiVersion: v1
kind: Service
metadata:
  name: {{ include "tyk-sre-app.fullname" . }}
  labels:
    {{- include "tyk-sre-app.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "tyk-sre-app.selectorLabels" . | nindent 4 }}
